---
- name: apt-get update
  apt:
    update_cache: yes
- name: apt upgrade
  apt:
    upgrade: safe
- name: install packages
  apt:
    name:
      - docker.io
      - ffmpeg
      - rsync
      - screen
      - htop
      - iptables
